INVALID_CHECKSUM = "invalidchecksum123"
PHAGE_MD5 = "3332ed720ac7eaa9b3655c06f6b9e196"

REDIRECT_LOCATION_BASE = "http://refget-test.s3-website.eu-west-2.amazonaws.com"
REDIRECT_LOCATION_SEQ = REDIRECT_LOCATION_BASE + "/sequence"
REDIRECT_LOCATION_METADATA = REDIRECT_LOCATION_BASE + "/metadata/json"

REDIRECT_LOCATION_PHAGE_MD5 = \
    REDIRECT_LOCATION_SEQ + "/" + PHAGE_MD5
REDIRECT_LOCATION_INVALID_MD5 = \
    REDIRECT_LOCATION_SEQ + "/" + INVALID_CHECKSUM

REDIRECT_LOCATION_INVALID_MD5_METADATA = \
    REDIRECT_LOCATION_METADATA + "/" + INVALID_CHECKSUM + ".json"
REDIRECT_LOCATION_PHAGE_MD5_METADATA = \
    REDIRECT_LOCATION_METADATA + "/" + PHAGE_MD5 + ".json"

PHAGE_SUBSEQ_100_400 = \
"CGAATTAAATCGAAGTGGACTGCTGGCGGAAAATGAGAAAATTCGACCTATCCTTGCGCAGCTCGAGAAGCTCTTA" \
+ "CTTTGCGACCTTTCGCCATCAACTAACGATTCTGTCAAAAACTGACGCGTTGGATGAGGAGAAGTGGCTTAATA" \
+ "TGCTTGGCACGTTCGTCAAGGACTGGTTTAGATATGAGTCACATTTTGTTCATGGTAGAGATTCTCTTGTTGAC" \
+ "ATTTTAAAAGAGCGTGGATTACTATCTGAGTCCGATGCTGTTCAACCACTAATAGGTAAGAAATCATGAGTCAA" \
+ "GT"